import { writable, derived } from 'svelte/store'

// Default language
const DEFAULT_LANGUAGE = 'en'

// English translations as the source of truth
const en = {
  'version-value': '1.4.0',
  'send-webhook': 'Send Discord Webhook',
  'no-presets': 'No Presets',
  'webhook-url': 'Webhook URL',
  name: 'Name',
  avatar: 'Avatar URL',
  message: 'Message',
  send: 'Send',
  bot: 'Bot',
  'message-placeholder': 'Enter your message here',
  token: 'Token',
  login: 'Login',
  logout: 'Logout',
  invite: 'Invite',
  status: 'Status',
  activity: 'Activity',
  'status-details': 'Status Details',
  'status-details-placeholder': 'Enter your status details here',
  'twitch-url': 'Twitch.tv URL',
  'update-status': 'Update Status',
  settings: 'Settings',
  theme: 'Theme',
  'show-token': 'Show Token',
  'show-token-description': 'Display API keys and tokens in plain text instead of hidden',
  'hide-output': 'Hide Output Preview',
  'hide-output-description': 'Hide the command output preview panel in the editor',
  language: 'Language',
  about: 'About',
  'bot-state': 'Bot State',
  value: 'Value',
  'run-code': 'Run Code',
  'run-code-placeholder': 'Enter JavaScript code here...',
  output: 'Output',
  run: 'Run',
  stats: 'Stats',
  users: 'Users',
  'messages-sent': 'Messages Sent',
  'messages-received': 'Messages Received',
  'on-join': 'On Join',
  'on-leave': 'On Leave',
  'on-ban': 'On Ban',
  'private-messages-received': 'Private Messages Received',
  servers: 'Servers',
  commands: 'Commands',
  'time-spent-in-app': 'Time Spent in App',
  'webhooks-sent': 'Webhooks Sent',
  cancel: 'Cancel',
  'add-command': 'Add Command',
  'no-commands-found': 'No commands found.',
  'no-commands': 'No Commands',
  'add-command-hint': 'Add a command to get started',
  'command-exported-to-clipboard': 'Command exported to clipboard!',
  'import-json-command': 'Import JSON command',
  delete: 'Delete',
  'are-you-sure-you-want-to-delete-the-command': 'Are you sure you want to delete the command?',
  'tip-shift-click-delete': 'Tip: Shift+click the delete button to skip this confirmation.',
  'open-quote': '"',
  'close-quote': '”',
  'edit-command': 'Edit Command',
  'choose-command-type': 'Choose Command Type',
  'message-received': 'Message Received',
  'private-message-received': 'Private Message Received',
  'member-join': 'Member Join',
  'member-leave': 'Member Leave',
  'member-ban': 'Member Ban',
  reaction: 'Reaction',
  'bot-login': 'Bot Login',
  command: 'Command',
  description: 'Description',
  'reaction-placeholder': 'Emoji ID or name or 😊',
  'specific-message-only': 'Specific Message Only',
  'message-id': 'Message ID',
  phrase: 'Phrase',
  'requires-role': 'Requires Role',
  'required-role': 'Required Role',
  'role-id': 'Role ID',
  'requires-admin': 'Requires Admin',
  'send-message': 'Send Message',
  'channel-message': 'Channel Message',
  'as-reply': 'As Reply',
  'send-channel-embed': 'Send Channel Embed',
  'channel-embed-title': 'Channel Embed Title',
  'channel-embed-description': 'Channel Embed Description',
  'channel-embed-footer': 'Channel Embed Footer',
  'channel-embed-image': 'Channel Embed Image',
  'channel-embed-thumbnail': 'Channel Embed Thumbnail',
  'channel-embed-color': 'Channel Embed Color',
  'send-in-specific-channel': 'Send in Specific Channel',
  'specific-channel': 'Specific Channel',
  'channel-whitelist': 'Channel Whitelist',
  'server-whitelist': 'Server Whitelist',
  'send-private-message': 'Send Private Message',
  'private-message': 'Private Message',
  'send-private-embed': 'Send Private Embed',
  'private-embed-title': 'Private Embed Title',
  'private-embed-description': 'Private Embed Description',
  'private-embed-footer': 'Private Embed Footer',
  'private-embed-image': 'Private Embed Image',
  'private-embed-thumbnail': 'Private Embed Thumbnail',
  'private-embed-color': 'Private Embed Color',
  'react-to-message': 'React To Message',
  'ignore-error-message': 'Ignore Error Message',
  'delete-if-contains': 'Delete If Contains',
  'delete-if-strings': 'Delete If Strings',
  'delete-after': 'Delete After',
  'delete-x-times': 'Delete X Times',
  'delete-num': 'Delete Num',
  'is-nsfw': 'Is NSFW',
  cooldown: 'Cooldown',
  'cooldown-type': 'Cooldown Type',
  'cooldown-user': 'User',
  'cooldown-server': 'Server',
  'cooldown-global': 'Global',
  'cooldown-message': 'Cooldown Message',
  'cooldown-hint': 'Set to 0 or leave empty to disable.',
  moderation: 'Moderation',
  kick: 'Kick',
  ban: 'Ban',
  'voice-mute': 'Voice Mute',
  'role-assigner': 'Role Assign',
  'role-to-assign': 'Role To Assign',
  'update-command': 'Update Command',
  action: 'Action',
  hours: 'h',
  minutes: 'm',
  seconds: 's',
  'status-online': 'Online',
  'status-idle': 'Idle',
  'status-dnd': 'Do Not Disturb',
  'status-invisible': 'Invisible',
  'activity-playing': 'Playing',
  'activity-streaming': 'Streaming',
  'activity-listening': 'Listening',
  'activity-watching': 'Watching',
  'activity-none': 'None',
  'activity-competing': 'Competing',
  'language-tooltip': 'The language may be machine translated.',
  'no-state-data': 'No state data found.',
  help: 'Help',
  details: 'Details',
  actions: 'Actions',
  'command-trigger': 'Command Trigger',
  'command-only': 'Command Only',
  'starts-with': 'Starts With',
  'startup-js': 'Startup JavaScript',
  save: 'Save',
  'restart-js-engine': 'Restart JS Engine',
  export: 'Export',
  import: 'Import',
  general: 'General',
  openai: 'OpenAI',
  'openai-api-key': 'OpenAI API Key',
  'enter-your-openai-api-key': 'Enter your OpenAI API key...',
  'openai-model': 'OpenAI Model',
  'developer-prompt': 'Developer Prompt',
  'enter-your-custom-developer-prompt': 'Enter your custom developer prompt...',
  'disable-reasoning-api': 'Disable Reasoning API',
  'disable-reasoning-api-description':
    'Use standard API instead of streaming reasoning API for thinking models (GPT-5.1, GPT-5.2)',
  advanced: 'Advanced',
  'use-legacy-interpreter': 'Use Legacy Interpreter',
  'use-legacy-interpreter-description':
    'Use the old regex-based template interpreter instead of the new AST-based one',
  // AI Chat strings
  'ai-assistant': 'AI Assistant',
  'ai-chat-started': 'AI assistant ready to help edit command:',
  'proposed-changes': 'Proposed Changes',
  changes: 'changes',
  'accept-changes': 'Accept Changes',
  reject: 'Reject',
  'changes-applied': 'Changes applied successfully',
  'changes-rejected': 'Changes rejected',
  'describe-changes': 'Describe what you want to change...',
  'api-key-needed': 'OpenAI API key required',
  'openai-key-required': 'Please add your OpenAI API key in Settings to use the AI assistant.',
  'select-model': 'Select AI Model',
  'select-context': 'Select Context',
  'total-tokens': 'Total tokens used',
  'new-chat': 'New Chat',
  'clear-chat': 'Clear Chat',
  close: 'Close',
  'suggest-improvements': 'Suggest improvements',
  'make-funnier': 'Make funnier',
  'add-randomness': 'Add randomness',
  'use-mentions': 'Use mentions',
  'add-counter': 'Add counter',
  'quick-suggest-improvements':
    'Analyze this command and suggest improvements to make it more effective, user-friendly, or feature-rich',
  'quick-make-funnier': 'Make this command response funnier and more engaging',
  'quick-add-random': 'Add random variations to the response using $random{}',
  'quick-add-mentions': 'Include user mentions like $name and $botName in the response',
  'quick-add-counter': 'Add a counter using $eval and botState to track command usage',
  // Interaction Commands
  interactions: 'Interactions',
  'add-interaction': 'Add Interaction',
  'edit-interaction': 'Edit Interaction',
  'no-interactions-found': 'No interactions found.',
  'no-interactions': 'No Interactions',
  'add-interaction-hint': 'Add an interaction to get started',
  'sync-all': 'Sync All',
  registered: 'Registered',
  'not-registered': 'Not Registered',
  register: 'Register',
  unregister: 'Unregister',
  options: 'Options',
  buttons: 'Buttons',
  edit: 'Edit',
  'edit-json-value': 'Edit JSON Value',
  'confirm-delete': 'Confirm Delete',
  'confirm-delete-variable': 'Are you sure you want to delete the variable',
  'delete-interaction-confirm': 'Are you sure you want to delete interaction',
  'command-details': 'Command Details',
  'command-name': 'Command Name',
  'command-name-hint': 'Lowercase, no spaces. Use letters, numbers, hyphens, underscores.',
  'command-description': 'Command Description',
  'command-options': 'Command Options',
  'add-option': 'Add Option',
  'no-options-hint': 'No options. Add options to let users provide input to your command.',
  'option-name': 'Option Name',
  'option-type': 'Option Type',
  'option-required': 'Required',
  required: 'Required',
  'option-description': 'Option Description',
  'root-action': 'Command Response',
  'root-action-hint': 'What happens when the slash command is used.',
  'add-button': 'Add Button',
  'no-buttons-hint': 'No buttons. Add buttons to create interactive responses.',
  'max-buttons-warning': 'Maximum 5 buttons per row. Discord limits buttons to 5 per action row.',
  'response-buttons': 'Response Buttons',
  'no-response-buttons-hint': 'Add buttons to attach to this response.',
  'nesting-level': 'Level',
  'button-label': 'Button Label',
  'button-style': 'Button Style',
  'button-custom-id': 'Custom ID',
  'button-emoji': 'Emoji',
  'button-url': 'URL',
  'button-disabled': 'Disabled',
  'button-action': 'Button Action',
  'style-primary': 'Primary',
  'style-secondary': 'Secondary',
  'style-success': 'Success',
  'style-danger': 'Danger',
  'style-link': 'Link',
  ephemeral: 'Ephemeral (only visible to user)',
  'defer-reply': 'Defer Reply (for slow actions)',
  'add-action': 'Add Action',
  'all-actions-added': 'All actions added',
  'interaction-send-channel-message': 'Send Channel Message',
  'interaction-send-channel-embed': 'Send Channel Embed',
  'embed-title': 'Title',
  'embed-description': 'Description',
  'embed-color': 'Color (hex)',
  'embed-image': 'Image URL',
  'embed-thumbnail': 'Thumbnail URL',
  'embed-footer': 'Footer',
  disabled: 'Disabled',
  search: 'Search',
  // Validation messages
  'fix-errors-to-save': 'Fix errors to save',
  'description-required': 'Description is required',
  'command-required': 'Command is required',
  'message-is-required': 'Message is required',
  'embed-field-required': 'At least one embed field is required',
  'channel-id-required': 'Channel ID is required',
  'channel-ids-required': 'Channel IDs are required',
  'server-ids-required': 'Server IDs are required',
  'reaction-required': 'Reaction is required',
  'delete-strings-required': 'Delete strings are required',
  'delete-number-required': 'Delete number must be at least 1',
  'role-id-is-required': 'Role ID is required',
  'name-is-required': 'Name is required',
  'name-invalid-format':
    'Must be 1-32 characters with letters, numbers, hyphens, underscores, or apostrophes',
  'description-too-long': 'Description must be 1-100 characters',
  'duplicate-option-name': 'Duplicate option name',
  'no-actions-added-hint': 'No actions added. Add at least one action.',
  'action-incompatible-with-type': 'This action has no effect for the selected event type',
  'send-channel-message': 'Send Channel Message',
  // API Auth strings
  account: 'Account',
  'sign-in': 'Sign In',
  'sign-out': 'Sign Out',
  'signed-in-as': 'Signed in as',
  username: 'Username',
  password: 'Password',
  'need-account': "Don't have an account? Register",
  'have-account': 'Already have an account? Login',
  // Onboarding and tips
  'got-it': 'Got it',
  'onboarding-getting-started': 'Getting Started',
  'onboarding-enter-token-message':
    'Visit the Discord Developer Portal to create a bot and copy its token.',
  'onboarding-open-portal': 'Open Portal',
  'onboarding-create-command-message': 'Create a command so your bot has something to do.',
  'onboarding-go-to-commands': 'Go to Commands',
  'onboarding-host-bot-message': 'Press Login to bring your bot online!',
  webhooks: 'Webhooks',
  debugger: 'Debugger',
  'tip-commands-body':
    'Commands define how your bot responds to messages. Create one, set a trigger word, then add actions like Send Message.',
  'tip-webhooks-body':
    'Send messages to Discord channels without hosting a bot. Paste a webhook URL from your Discord server settings.',
  'tip-interactions-body':
    'Interactions are Discord slash commands. Create one, then tap Sync to register it with Discord.',
  'tip-debugger-body':
    'Bot State shows persistent variables from your commands. Console lets you test JavaScript snippets against the bot context.',
  // Command Repository strings
  'command-repository': 'Command Repository',
  newest: 'Newest',
  'most-downloaded': 'Most Downloaded',
  browse: 'Browse',
  'my-shared-commands': 'My Shared Commands',
  'search-commands': 'Search commands...',
  dismiss: 'Dismiss',
  'no-commands-in-repository': 'No commands found in the repository.',
  'try-different-search': 'Try a different search term.',
  preview: 'Preview',
  downloads: 'downloads',
  'no-shared-commands': "You haven't shared any commands yet.",
  'share-commands-hint': 'Share commands from the command editor to see them here.',
  'confirm-delete-shared-command':
    'Are you sure you want to delete this command from the repository?',
  'delete-command-failed': 'Failed to delete command',
  'import-command-failed': 'Failed to import command',
  'browse-repository': 'Browse Repository',
  // Share Command Modal strings
  share: 'Share',
  'share-command': 'Share Command',
  'command-shared-successfully': 'Command shared successfully!',
  type: 'Type',
  trigger: 'Trigger',
  'share-info': 'Your command will be publicly available in the repository for others to import.',
  'no-command-selected': 'No command selected.',
  // Command Preview Modal strings
  'command-preview': 'Command Preview',
  'no-embed-configured': 'No embed configured',
  'channel-id': 'Channel ID',
  'deletes-command-message': 'Deletes the command message after sending',
  messages: 'message(s)',
  'kicks-mentioned-user': 'Kicks the mentioned user',
  'bans-mentioned-user': 'Bans the mentioned user',
  'voice-mutes-mentioned-user': 'Voice mutes the mentioned user',
  'requires-administrator': 'Requires Administrator Role',
  'requires-nsfw-channel': 'Requires NSFW Channel',
  'no-actions-configured': 'No actions configured for this command.'
} as const

// Derive the valid key type from English dictionary
export type TranslationKey = keyof typeof en

// Other languages must have the same keys as English
type TranslationDictionary = Record<TranslationKey, string>

type Languages = {
  [lang: string]: TranslationDictionary
}

// Translation dictionaries
const translations: Languages = {
  en,
  es: {
    'version-value': '1.4.0',
    'send-webhook': 'Enviar Webhook de Discord',
    'no-presets': 'Sin preajustes',
    'webhook-url': 'URL del Webhook',
    name: 'Nombre',
    avatar: 'URL del Avatar',
    message: 'Mensaje',
    send: 'Enviar',
    bot: 'Bot',
    'message-placeholder': 'Escribe tu mensaje aquí',
    token: 'Token',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    invite: 'Invitar',
    status: 'Estado',
    activity: 'Actividad',
    'status-details': 'Detalles del estado',
    'status-details-placeholder': 'Escribe los detalles de tu estado aquí',
    'twitch-url': 'URL de Twitch.tv',
    'update-status': 'Actualizar estado',
    settings: 'Configuración',
    theme: 'Tema',
    'show-token': 'Mostrar token',
    'show-token-description': 'Mostrar claves API y tokens en texto plano en lugar de ocultos',
    'hide-output': 'Ocultar vista previa de salida',
    'hide-output-description':
      'Ocultar el panel de vista previa de salida del comando en el editor',
    language: 'Idioma',
    about: 'Acerca de',
    'bot-state': 'Estado del bot',
    value: 'Valor',
    'run-code': 'Ejecutar código',
    'run-code-placeholder': 'Escribe el código JavaScript aquí...',
    output: 'Salida',
    run: 'Ejecutar',
    stats: 'Estadísticas',
    users: 'Usuarios',
    'messages-sent': 'Mensajes enviados',
    'messages-received': 'Mensajes recibidos',
    'on-join': 'En unirse',
    'on-leave': 'En abandonar',
    'on-ban': 'En banear',
    'private-messages-received': 'Mensajes privados recibidos',
    servers: 'Servidores',
    commands: 'Comandos',
    'time-spent-in-app': 'Tiempo en la aplicación',
    'webhooks-sent': 'Webhooks enviados',
    cancel: 'Cancelar',
    'add-command': 'Añadir comando',
    'no-commands-found': 'No se encontraron comandos.',
    'no-commands': 'Sin comandos',
    'add-command-hint': 'Añade un comando para empezar',
    'command-exported-to-clipboard': '¡Comando exportado al portapapeles!',
    'import-json-command': 'Importar comando JSON',
    delete: 'Eliminar',
    'are-you-sure-you-want-to-delete-the-command':
      '¿Estás seguro de que quieres eliminar el comando?',
    'tip-shift-click-delete':
      'Consejo: Mantén Shift y haz clic en el botón eliminar para omitir esta confirmación.',
    'open-quote': '"',
    'close-quote': '”',
    'edit-command': 'Editar comando',
    'choose-command-type': 'Escoge el tipo de comando',
    'message-received': 'Mensaje recibido',
    'private-message-received': 'Mensaje privado recibido',
    'member-join': 'Miembro se unió',
    'member-leave': 'Miembro abandonó',
    'member-ban': 'Miembro baneado',
    reaction: 'Reacción',
    'bot-login': 'Inicio de sesión del bot',
    command: 'Comando',
    description: 'Descripción',
    'reaction-placeholder': 'ID de emoji o nombre o 😊',
    'specific-message-only': 'Mensaje específico solo',
    'message-id': 'ID de mensaje',
    phrase: 'Frase',
    'requires-role': 'Requiere rol',
    'required-role': 'Rol requerido',
    'role-id': 'ID de rol',
    'requires-admin': 'Requiere admin',
    'send-message': 'Enviar mensaje',
    'channel-message': 'Mensaje de canal',
    'as-reply': 'Como respuesta',
    'send-channel-embed': 'Enviar embed de canal',
    'channel-embed-title': 'Título del embed de canal',
    'channel-embed-description': 'Descripción del embed de canal',
    'channel-embed-footer': 'Pie de página del embed de canal',
    'channel-embed-image': 'Imagen del embed de canal',
    'channel-embed-thumbnail': 'Miniatura del embed de canal',
    'channel-embed-color': 'Color del embed de canal',
    'send-in-specific-channel': 'Enviar en canal específico',
    'specific-channel': 'Canal específico',
    'channel-whitelist': 'Lista blanca de canales',
    'server-whitelist': 'Lista blanca de servidores',
    'send-private-message': 'Enviar mensaje privado',
    'private-message': 'Mensaje privado',
    'send-private-embed': 'Enviar embed privado',
    'private-embed-title': 'Título del embed privado',
    'private-embed-description': 'Descripción del embed privado',
    'private-embed-footer': 'Pie de página del embed privado',
    'private-embed-image': 'Imagen del embed privado',
    'private-embed-thumbnail': 'Miniatura del embed privado',
    'private-embed-color': 'Color del embed privado',
    'react-to-message': 'React to Message',
    'ignore-error-message': 'Ignorar mensaje de error',
    'delete-if-contains': 'Eliminar si contiene',
    'delete-if-strings': 'Eliminar si cadenas',
    'delete-after': 'Eliminar después',
    'delete-x-times': 'Eliminar X veces',
    'delete-num': 'Eliminar número',
    'is-nsfw': 'Es NSFW',
    cooldown: 'Enfriamiento',
    'cooldown-type': 'Tipo de enfriamiento',
    'cooldown-user': 'Usuario',
    'cooldown-server': 'Servidor',
    'cooldown-global': 'Global',
    'cooldown-message': 'Mensaje de enfriamiento',
    'cooldown-hint': 'Pon 0 o déjalo vacío para desactivar.',
    moderation: 'Moderación',
    kick: 'Expulsar',
    ban: 'Banear',
    'voice-mute': 'Silenciar voz',
    'role-assigner': 'Asignar rol',
    'role-to-assign': 'Rol a asignar',
    'update-command': 'Actualizar comando',
    action: 'Acción',
    hours: 'h',
    minutes: 'm',
    seconds: 's',
    'status-online': 'En línea',
    'status-idle': 'Ocioso',
    'status-dnd': 'No Disturbiar',
    'status-invisible': 'Invisible',
    'activity-playing': 'Jugando',
    'activity-streaming': 'Transmitiendo',
    'activity-listening': 'Escuchando',
    'activity-watching': 'Viendo',
    'activity-none': 'Ninguno',
    'activity-competing': 'Competiendo',
    'language-tooltip': 'El idioma puede ser una traducción automática.',
    'no-state-data': 'No hay datos de estado.',
    help: 'Ayuda',
    details: 'Detalles',
    actions: 'Acciones',
    'command-trigger': 'Disparador de comando',
    'command-only': 'Solo comando',
    'starts-with': 'Comienza con',
    'startup-js': 'JavaScript de inicio',
    save: 'Guardar',
    'restart-js-engine': 'Reiniciar motor JS',
    export: 'Exportar',
    import: 'Importar',
    general: 'General',
    openai: 'OpenAI',
    'openai-api-key': 'Clave de API de OpenAI',
    'enter-your-openai-api-key': 'Introduce tu clave de API de OpenAI...',
    'openai-model': 'Modelo OpenAI',
    'developer-prompt': 'Prompt del Desarrollador',
    'enter-your-custom-developer-prompt': 'Introduce tu prompt de desarrollador personalizado...',
    'disable-reasoning-api': 'Desactivar API de Razonamiento',
    'disable-reasoning-api-description':
      'Usar API estándar en lugar de API de razonamiento para modelos de pensamiento (GPT-5.1, GPT-5.2)',
    advanced: 'Avanzado',
    'use-legacy-interpreter': 'Usar Intérprete Antiguo',
    'use-legacy-interpreter-description':
      'Usar el antiguo intérprete de plantillas basado en regex en lugar del nuevo basado en AST',
    // AI Chat strings
    'ai-assistant': 'Asistente IA',
    'ai-chat-started': 'Asistente IA listo para editar comando:',
    'proposed-changes': 'Cambios Propuestos',
    changes: 'cambios',
    'accept-changes': 'Aceptar Cambios',
    reject: 'Rechazar',
    'changes-applied': 'Cambios aplicados exitosamente',
    'changes-rejected': 'Cambios rechazados',
    'describe-changes': 'Describe lo que quieres cambiar...',
    'api-key-needed': 'Se requiere clave API de OpenAI',
    'openai-key-required':
      'Por favor agrega tu clave API de OpenAI en Configuración para usar el asistente IA.',
    'select-model': 'Seleccionar Modelo IA',
    'select-context': 'Seleccionar Contexto',
    'total-tokens': 'Tokens totales usados',
    'new-chat': 'Nueva Conversación',
    'clear-chat': 'Limpiar Chat',
    close: 'Cerrar',
    'suggest-improvements': 'Sugerir mejoras',
    'make-funnier': 'Hacer más divertido',
    'add-randomness': 'Agregar aleatoriedad',
    'use-mentions': 'Usar menciones',
    'add-counter': 'Agregar contador',
    'quick-suggest-improvements':
      'Analiza este comando y sugiere mejoras para hacerlo más efectivo, fácil de usar o con más características',
    'quick-make-funnier': 'Hacer esta respuesta de comando más divertida y atractiva',
    'quick-add-random': 'Agregar variaciones aleatorias a la respuesta usando $random{}',
    'quick-add-mentions': 'Incluir menciones de usuario como $name y $botName en la respuesta',
    'quick-add-counter':
      'Agregar un contador usando $eval y botState para rastrear uso del comando',
    // Interaction Commands
    interactions: 'Interacciones',
    'add-interaction': 'Añadir Interacción',
    'edit-interaction': 'Editar Interacción',
    'no-interactions-found': 'No se encontraron interacciones.',
    'no-interactions': 'Sin interacciones',
    'add-interaction-hint': 'Añade una interacción para empezar',
    'sync-all': 'Sincronizar Todo',
    registered: 'Registrado',
    'not-registered': 'No Registrado',
    unregister: 'Anular Registro',
    options: 'Opciones',
    buttons: 'Botones',
    edit: 'Editar',
    'edit-json-value': 'Editar Valor JSON',
    'confirm-delete': 'Confirmar Eliminación',
    'confirm-delete-variable': '¿Estás seguro de que quieres eliminar la variable',
    'delete-interaction-confirm': '¿Estás seguro de que quieres eliminar la interacción',
    'command-details': 'Detalles del Comando',
    'command-name': 'Nombre del Comando',
    'command-name-hint': 'Minúsculas, sin espacios. Usa letras, números, guiones, guiones bajos.',
    'command-description': 'Descripción del Comando',
    'command-options': 'Opciones del Comando',
    'add-option': 'Añadir Opción',
    'no-options-hint':
      'Sin opciones. Añade opciones para permitir que los usuarios proporcionen entrada a tu comando.',
    'option-name': 'Nombre de Opción',
    'option-type': 'Tipo de Opción',
    'option-required': 'Requerido',
    required: 'Requerido',
    'option-description': 'Descripción de Opción',
    'root-action': 'Respuesta del Comando',
    'root-action-hint': 'Qué sucede cuando se usa el comando de barra.',
    'add-button': 'Añadir Botón',
    'no-buttons-hint': 'Sin botones. Añade botones para crear respuestas interactivas.',
    'max-buttons-warning':
      'Máximo 5 botones por fila. Discord limita los botones a 5 por fila de acción.',
    'response-buttons': 'Botones de Respuesta',
    'no-response-buttons-hint': 'Añade botones para adjuntar a esta respuesta.',
    'nesting-level': 'Nivel',
    'button-label': 'Etiqueta del Botón',
    'button-style': 'Estilo del Botón',
    'button-custom-id': 'ID Personalizado',
    'button-emoji': 'Emoji',
    'button-url': 'URL',
    'button-disabled': 'Deshabilitado',
    'button-action': 'Acción del Botón',
    'style-primary': 'Primario',
    'style-secondary': 'Secundario',
    'style-success': 'Éxito',
    'style-danger': 'Peligro',
    'style-link': 'Enlace',
    ephemeral: 'Efímero (solo visible para el usuario)',
    'defer-reply': 'Diferir Respuesta (para acciones lentas)',
    'add-action': 'Añadir Acción',
    'all-actions-added': 'Todas las acciones añadidas',
    'interaction-send-channel-message': 'Enviar Mensaje de Canal',
    'interaction-send-channel-embed': 'Enviar Embed de Canal',
    'embed-title': 'Título',
    'embed-description': 'Descripción',
    'embed-color': 'Color (hex)',
    'embed-image': 'URL de Imagen',
    'embed-thumbnail': 'URL de Miniatura',
    'embed-footer': 'Pie de página',
    disabled: 'Deshabilitado',
    search: 'Buscar',
    // Validation messages
    'fix-errors-to-save': 'Corregir errores para guardar',
    'description-required': 'La descripción es obligatoria',
    'command-required': 'El comando es obligatorio',
    'message-is-required': 'El mensaje es obligatorio',
    'embed-field-required': 'Se requiere al menos un campo de embed',
    'channel-id-required': 'Se requiere el ID del canal',
    'channel-ids-required': 'Los IDs de canal son obligatorios',
    'server-ids-required': 'Los IDs de servidor son obligatorios',
    'reaction-required': 'Se requiere la reacción',
    'delete-strings-required': 'Se requieren las cadenas de eliminación',
    'delete-number-required': 'El número de eliminación debe ser al menos 1',
    'role-id-is-required': 'Se requiere el ID del rol',
    'name-is-required': 'El nombre es obligatorio',
    'name-invalid-format':
      'Debe tener 1-32 caracteres con letras, números, guiones, guiones bajos o apóstrofes',
    'description-too-long': 'La descripción debe tener 1-100 caracteres',
    'duplicate-option-name': 'Nombre de opción duplicado',
    'no-actions-added-hint': 'No hay acciones añadidas. Añade al menos una acción.',
    'action-incompatible-with-type':
      'Esta acción no tiene efecto para el tipo de evento seleccionado',
    'send-channel-message': 'Enviar mensaje de canal',
    // API Auth strings
    account: 'Cuenta',
    'sign-in': 'Iniciar sesión',
    'sign-out': 'Cerrar sesión',
    'signed-in-as': 'Conectado como',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    register: 'Registrarse',
    'need-account': '¿No tienes cuenta? Regístrate',
    'have-account': '¿Ya tienes cuenta? Iniciar sesión',
    // Onboarding and tips
    'got-it': 'Entendido',
    'onboarding-getting-started': 'Primeros pasos',
    'onboarding-enter-token-message':
      'Visita el Portal de Desarrolladores de Discord para crear un bot y copiar su token.',
    'onboarding-open-portal': 'Abrir Portal',
    'onboarding-create-command-message': 'Crea un comando para que tu bot tenga algo que hacer.',
    'onboarding-go-to-commands': 'Ir a Comandos',
    'onboarding-host-bot-message': '¡Pulsa Iniciar sesión para poner tu bot en línea!',
    webhooks: 'Webhooks',
    debugger: 'Depurador',
    'tip-commands-body':
      'Los comandos definen cómo responde tu bot a los mensajes. Crea uno, configura una palabra de activación y luego añade acciones como Enviar mensaje.',
    'tip-webhooks-body':
      'Envía mensajes a canales de Discord sin alojar un bot. Pega una URL de webhook desde la configuración de tu servidor de Discord.',
    'tip-interactions-body':
      'Las interacciones son comandos slash de Discord. Crea una y luego pulsa Sincronizar para registrarla con Discord.',
    'tip-debugger-body':
      'El estado del bot muestra variables persistentes de tus comandos. La consola te permite probar fragmentos de JavaScript con el contexto del bot.',
    // Command Repository strings
    'command-repository': 'Repositorio de Comandos',
    newest: 'Más Reciente',
    'most-downloaded': 'Más Descargados',
    browse: 'Explorar',
    'my-shared-commands': 'Mis Comandos Compartidos',
    'search-commands': 'Buscar comandos...',
    dismiss: 'Descartar',
    'no-commands-in-repository': 'No se encontraron comandos en el repositorio.',
    'try-different-search': 'Prueba con otro término de búsqueda.',
    preview: 'Vista Previa',
    downloads: 'descargas',
    'no-shared-commands': 'Aún no has compartido ningún comando.',
    'share-commands-hint': 'Comparte comandos desde el editor de comandos para verlos aquí.',
    'confirm-delete-shared-command':
      '¿Estás seguro de que quieres eliminar este comando del repositorio?',
    'delete-command-failed': 'Error al eliminar el comando',
    'import-command-failed': 'Error al importar el comando',
    'browse-repository': 'Explorar Repositorio',
    // Share Command Modal strings
    share: 'Compartir',
    'share-command': 'Compartir Comando',
    'command-shared-successfully': '¡Comando compartido exitosamente!',
    type: 'Tipo',
    trigger: 'Disparador',
    'share-info':
      'Tu comando estará disponible públicamente en el repositorio para que otros lo importen.',
    'no-command-selected': 'Ningún comando seleccionado.',
    // Command Preview Modal strings
    'command-preview': 'Vista Previa del Comando',
    'no-embed-configured': 'Sin embed configurado',
    'channel-id': 'ID del Canal',
    'deletes-command-message': 'Elimina el mensaje del comando después de enviarlo',
    messages: 'mensaje(s)',
    'kicks-mentioned-user': 'Expulsa al usuario mencionado',
    'bans-mentioned-user': 'Banea al usuario mencionado',
    'voice-mutes-mentioned-user': 'Silencia la voz del usuario mencionado',
    'requires-administrator': 'Requiere Rol de Administrador',
    'requires-nsfw-channel': 'Requiere Canal NSFW',
    'no-actions-configured': 'No hay acciones configuradas para este comando.'
  },
  ja: {
    'version-value': '1.4.0',
    'send-webhook': 'Discord Webhookを送信',
    'no-presets': 'プリセットなし',
    'webhook-url': 'Webhook URL',
    name: '名前',
    avatar: 'アバターURL',
    message: 'メッセージ',
    send: '送信',
    bot: 'ボット',
    'message-placeholder': 'ここにメッセージを入力してください',
    token: 'トークン',
    login: 'ログイン',
    logout: 'ログアウト',
    invite: '招待',
    status: 'ステータス',
    activity: 'アクティビティ',
    'status-details': 'ステータスの詳細',
    'status-details-placeholder': 'ここにステータスの詳細を入力してください',
    'twitch-url': 'Twitch.tv URL',
    'update-status': 'ステータスを更新',
    settings: '設定',
    theme: 'テーマ',
    'show-token': 'トークンを表示',
    'show-token-description': 'APIキーとトークンを非表示ではなくプレーンテキストで表示',
    'hide-output': '出力プレビューを非表示',
    'hide-output-description': 'エディターでコマンド出力プレビューパネルを非表示にする',
    language: '言語',
    about: '約',
    'bot-state': 'ボットの状態',
    value: '値',
    'run-code': 'コードを実行',
    'run-code-placeholder': 'ここにJavaScriptコードを入力してください...',
    output: '出力',
    run: '実行',
    stats: '統計',
    users: 'ユーザー',
    'messages-sent': '送信されたメッセージ',
    'messages-received': '受信したメッセージ',
    'on-join': '参加時',
    'on-leave': '退会時',
    'on-ban': '禁止時',
    'private-messages-received': '受信したプライベートメッセージ',
    servers: 'サーバー',
    commands: 'コマンド',
    'time-spent-in-app': 'アプリでの時間',
    'webhooks-sent': '送信されたWebhook',
    cancel: 'キャンセル',
    'add-command': 'コマンドを追加',
    'no-commands-found': 'コマンドが見つかりません。',
    'no-commands': 'コマンドなし',
    'add-command-hint': 'コマンドを追加して始めましょう',
    'command-exported-to-clipboard': 'コマンドがクリップボードにエクスポートされました！',
    'import-json-command': 'JSONコマンドをインポート',
    delete: '削除',
    'are-you-sure-you-want-to-delete-the-command': 'コマンドを削除してもよろしいですか？',
    'tip-shift-click-delete':
      'ヒント: Shiftキーを押しながら削除ボタンをクリックすると、この確認をスキップできます。',
    'open-quote': '「',
    'close-quote': '」',
    'edit-command': 'コマンドを編集',
    'choose-command-type': 'コマンドタイプを選択',
    'message-received': 'メッセージを受信',
    'private-message-received': 'プライベートメッセージを受信',
    'member-join': 'メンバー参加',
    'member-leave': 'メンバー退会',
    'member-ban': 'メンバー禁止',
    reaction: 'リアクション',
    'bot-login': 'ボットログイン',
    command: 'コマンド',
    description: '説明',
    'reaction-placeholder': '絵文字IDまたは名前または😊',
    'specific-message-only': '特定のメッセージのみ',
    'message-id': 'メッセージID',
    phrase: 'フレーズ',
    'requires-role': '役割が必要',
    'required-role': '必要な役割',
    'role-id': '役割ID',
    'requires-admin': '管理者が必要',
    'send-message': 'メッセージを送信',
    'channel-message': 'チャンネルメッセージ',
    'as-reply': '返信として',
    'send-channel-embed': 'チャンネル埋め込みを送信',
    'channel-embed-title': 'チャンネル埋め込みタイトル',
    'channel-embed-description': 'チャンネル埋め込み説明',
    'channel-embed-footer': 'チャンネル埋め込みフッター',
    'channel-embed-image': 'チャンネル埋め込み画像',
    'channel-embed-thumbnail': 'チャンネル埋め込みサムネイル',
    'channel-embed-color': 'チャンネル埋め込み色',
    'send-in-specific-channel': '特定チャンネルに送信',
    'specific-channel': '特定のチャンネル',
    'channel-whitelist': 'チャンネルホワイトリスト',
    'server-whitelist': 'サーバーホワイトリスト',
    'send-private-message': 'プライベートメッセージを送信',
    'private-message': 'プライベートメッセージ',
    'send-private-embed': 'プライベート埋め込みを送信',
    'private-embed-title': 'プライベート埋め込みタイトル',
    'private-embed-description': 'プライベート埋め込み説明',
    'private-embed-footer': 'プライベート埋め込みフッター',
    'private-embed-image': 'プライベート埋め込み画像',
    'private-embed-thumbnail': 'プライベート埋め込みサムネイル',
    'private-embed-color': 'プライベート埋め込み色',
    'react-to-message': 'メッセージに反応',
    'ignore-error-message': 'エラーメッセージを無視',
    'delete-if-contains': '含まれている場合は削除',
    'delete-if-strings': '文字列の場合は削除',
    'delete-after': '後に削除',
    'delete-x-times': 'X回削除',
    'delete-num': '削除数',
    'is-nsfw': 'NSFWです',
    cooldown: 'クールダウン',
    'cooldown-type': 'クールダウンタイプ',
    'cooldown-user': 'ユーザー',
    'cooldown-server': 'サーバー',
    'cooldown-global': 'グローバル',
    'cooldown-message': 'クールダウンメッセージ',
    'cooldown-hint': '0に設定するか空のままで無効化。',
    moderation: 'モデレーション',
    kick: 'キック',
    ban: '禁止',
    'voice-mute': 'ボイスミュート',
    'role-assigner': '役割を割り当てる',
    'role-to-assign': '割り当てる役割',
    'update-command': 'コマンドを更新',
    action: 'アクション',
    hours: '時間',
    minutes: '分',
    seconds: '秒',
    'status-online': 'オンライン',
    'status-idle': 'アイドル',
    'status-dnd': 'ドントディストラクト',
    'status-invisible': 'インビジブル',
    'activity-playing': 'プレイング',
    'activity-streaming': 'ストリーミング',
    'activity-listening': 'リスニング',
    'activity-watching': 'ウォッチング',
    'activity-none': 'ノーン',
    'activity-competing': 'コンペティング',
    'language-tooltip': '言語は自動翻訳される可能性があります。',
    'no-state-data': '状態データがありません。',
    help: 'ヘルプ',
    details: '詳細',
    actions: 'アクション',
    'command-trigger': 'コマンドトリガー',
    'command-only': 'コマンドのみ',
    'starts-with': 'で始まる',
    'startup-js': '起動JavaScript',
    save: '保存',
    'restart-js-engine': 'JSエンジンを再起動',
    export: 'エクスポート',
    import: 'インポート',
    general: '一般',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI APIキー',
    'enter-your-openai-api-key': 'OpenAI APIキーを入力してください...',
    'openai-model': 'OpenAIモデル',
    'developer-prompt': '開発者プロンプト',
    'enter-your-custom-developer-prompt': 'カスタム開発者プロンプトを入力してください...',
    'disable-reasoning-api': '推論APIを無効化',
    'disable-reasoning-api-description':
      '思考モデル（GPT-5.1、GPT-5.2）にストリーミング推論APIではなく標準APIを使用',
    advanced: '詳細設定',
    'use-legacy-interpreter': '旧インタープリターを使用',
    'use-legacy-interpreter-description':
      '新しいAST方式の代わりに古いregex方式のテンプレートインタープリターを使用',
    // AI Chat strings
    'ai-assistant': 'AIアシスタント',
    'ai-chat-started': 'AIアシスタントがコマンド編集の準備ができました:',
    'proposed-changes': '提案された変更',
    changes: '変更',
    'accept-changes': '変更を承認',
    reject: '拒否',
    'changes-applied': '変更が正常に適用されました',
    'changes-rejected': '変更が拒否されました',
    'describe-changes': '変更したい内容を説明してください...',
    'api-key-needed': 'OpenAI APIキーが必要です',
    'openai-key-required': 'AIアシスタントを使用するには、設定でOpenAI APIキーを追加してください。',
    'select-model': 'AIモデルを選択',
    'select-context': 'コンテキストを選択',
    'total-tokens': '合計トークン使用量',
    'new-chat': '新しいチャット',
    'clear-chat': 'チャットをクリア',
    close: '閉じる',
    'suggest-improvements': '改善案を提案',
    'make-funnier': 'もっと面白く',
    'add-randomness': 'ランダム性を追加',
    'use-mentions': 'メンションを使用',
    'add-counter': 'カウンターを追加',
    'quick-suggest-improvements':
      'このコマンドを分析し、より効果的、ユーザーフレンドリー、または機能豊かにするための改善を提案してください',
    'quick-make-funnier': 'このコマンドの応答をより面白く魅力的にする',
    'quick-add-random': '$random{}を使用して応答にランダムなバリエーションを追加',
    'quick-add-mentions': '$nameや$botNameなどのユーザーメンションを応答に含める',
    'quick-add-counter': '$evalとbotStateを使用してコマンド使用回数を追跡するカウンターを追加',
    // Interaction Commands
    interactions: 'インタラクション',
    'add-interaction': 'インタラクションを追加',
    'edit-interaction': 'インタラクションを編集',
    'no-interactions-found': 'インタラクションが見つかりません。',
    'no-interactions': 'インタラクションなし',
    'add-interaction-hint': 'インタラクションを追加して始めましょう',
    'sync-all': 'すべて同期',
    registered: '登録済み',
    'not-registered': '未登録',
    unregister: '登録解除',
    options: 'オプション',
    buttons: 'ボタン',
    edit: '編集',
    'edit-json-value': 'JSON値を編集',
    'confirm-delete': '削除の確認',
    'confirm-delete-variable': '変数を削除してもよろしいですか',
    'delete-interaction-confirm': 'インタラクションを削除してもよろしいですか',
    'command-details': 'コマンド詳細',
    'command-name': 'コマンド名',
    'command-name-hint': '小文字、スペースなし。文字、数字、ハイフン、アンダースコアを使用。',
    'command-description': 'コマンドの説明',
    'command-options': 'コマンドオプション',
    'add-option': 'オプションを追加',
    'no-options-hint':
      'オプションがありません。オプションを追加してユーザーがコマンドに入力できるようにします。',
    'option-name': 'オプション名',
    'option-type': 'オプションタイプ',
    'option-required': '必須',
    required: '必須',
    'option-description': 'オプションの説明',
    'root-action': 'コマンド応答',
    'root-action-hint': 'スラッシュコマンドが使用されたときの動作。',
    'add-button': 'ボタンを追加',
    'no-buttons-hint': 'ボタンがありません。ボタンを追加してインタラクティブな応答を作成します。',
    'max-buttons-warning': '1行最大5ボタン。Discordはアクション行あたり5ボタンに制限しています。',
    'response-buttons': '応答ボタン',
    'no-response-buttons-hint': 'この応答に添付するボタンを追加します。',
    'nesting-level': 'レベル',
    'button-label': 'ボタンラベル',
    'button-style': 'ボタンスタイル',
    'button-custom-id': 'カスタムID',
    'button-emoji': '絵文字',
    'button-url': 'URL',
    'button-disabled': '無効',
    'button-action': 'ボタンアクション',
    'style-primary': 'プライマリ',
    'style-secondary': 'セカンダリ',
    'style-success': '成功',
    'style-danger': '危険',
    'style-link': 'リンク',
    ephemeral: 'エフェメラル（ユーザーにのみ表示）',
    'defer-reply': '遅延応答（遅いアクション用）',
    'add-action': 'アクションを追加',
    'all-actions-added': 'すべてのアクションが追加されました',
    'interaction-send-channel-message': 'チャンネルメッセージを送信',
    'interaction-send-channel-embed': 'チャンネル埋め込みを送信',
    'embed-title': 'タイトル',
    'embed-description': '説明',
    'embed-color': '色（16進数）',
    'embed-image': '画像URL',
    'embed-thumbnail': 'サムネイルURL',
    'embed-footer': 'フッター',
    disabled: '無効',
    search: '検索',
    // Validation messages
    'fix-errors-to-save': '保存するにはエラーを修正してください',
    'description-required': '説明は必須です',
    'command-required': 'コマンドは必須です',
    'message-is-required': 'メッセージは必須です',
    'embed-field-required': '少なくとも1つの埋め込みフィールドが必要です',
    'channel-id-required': 'チャンネルIDが必要です',
    'channel-ids-required': 'チャンネルIDが必要です',
    'server-ids-required': 'サーバーIDが必要です',
    'reaction-required': 'リアクションが必要です',
    'delete-strings-required': '削除文字列が必要です',
    'delete-number-required': '削除数は1以上である必要があります',
    'role-id-is-required': 'ロールIDが必要です',
    'name-is-required': '名前は必須です',
    'name-invalid-format':
      '1〜32文字で、文字、数字、ハイフン、アンダースコア、アポストロフィを使用してください',
    'description-too-long': '説明は1〜100文字である必要があります',
    'duplicate-option-name': 'オプション名が重複しています',
    'no-actions-added-hint':
      'アクションが追加されていません。少なくとも1つのアクションを追加してください。',
    'action-incompatible-with-type': 'このアクションは選択されたイベントタイプでは効果がありません',
    'send-channel-message': 'チャンネルメッセージを送信',
    // API Auth strings
    account: 'アカウント',
    'sign-in': 'サインイン',
    'sign-out': 'サインアウト',
    'signed-in-as': 'ログイン中',
    username: 'ユーザー名',
    password: 'パスワード',
    register: '登録',
    'need-account': 'アカウントをお持ちでないですか？登録',
    'have-account': 'すでにアカウントをお持ちですか？ログイン',
    // Onboarding and tips
    'got-it': '了解',
    'onboarding-getting-started': 'はじめに',
    'onboarding-enter-token-message':
      'Discord Developer Portalでボットを作成し、トークンをコピーしてください。',
    'onboarding-open-portal': 'ポータルを開く',
    'onboarding-create-command-message': 'ボットが実行する内容としてコマンドを作成してください。',
    'onboarding-go-to-commands': 'コマンドへ移動',
    'onboarding-host-bot-message': 'ログインを押してボットをオンラインにしましょう！',
    webhooks: 'Webhook',
    debugger: 'デバッガー',
    'tip-commands-body':
      'コマンドは、ボットがメッセージにどう応答するかを定義します。コマンドを作成し、トリガー語を設定して、メッセージ送信などのアクションを追加します。',
    'tip-webhooks-body':
      'ボットをホストせずにDiscordチャンネルへメッセージを送信できます。Discordサーバー設定からWebhook URLを貼り付けてください。',
    'tip-interactions-body':
      'インタラクションはDiscordのスラッシュコマンドです。作成後、同期を押してDiscordに登録します。',
    'tip-debugger-body':
      'ボット状態にはコマンドの永続変数が表示されます。コンソールではボットのコンテキストでJavaScriptスニペットをテストできます。',
    // Command Repository strings
    'command-repository': 'コマンドリポジトリ',
    newest: '最新',
    'most-downloaded': '人気順',
    browse: '閲覧',
    'my-shared-commands': '共有したコマンド',
    'search-commands': 'コマンドを検索...',
    dismiss: '閉じる',
    'no-commands-in-repository': 'リポジトリにコマンドが見つかりません。',
    'try-different-search': '別の検索語を試してください。',
    preview: 'プレビュー',
    downloads: 'ダウンロード',
    'no-shared-commands': 'まだコマンドを共有していません。',
    'share-commands-hint': 'コマンドエディタからコマンドを共有すると、ここに表示されます。',
    'confirm-delete-shared-command': 'このコマンドをリポジトリから削除してもよろしいですか？',
    'delete-command-failed': 'コマンドの削除に失敗しました',
    'import-command-failed': 'コマンドのインポートに失敗しました',
    'browse-repository': 'リポジトリを閲覧',
    // Share Command Modal strings
    share: '共有',
    'share-command': 'コマンドを共有',
    'command-shared-successfully': 'コマンドが正常に共有されました！',
    type: 'タイプ',
    trigger: 'トリガー',
    'share-info': 'コマンドはリポジトリで公開され、他のユーザーがインポートできるようになります。',
    'no-command-selected': 'コマンドが選択されていません。',
    // Command Preview Modal strings
    'command-preview': 'コマンドプレビュー',
    'no-embed-configured': '埋め込みが設定されていません',
    'channel-id': 'チャンネルID',
    'deletes-command-message': '送信後にコマンドメッセージを削除',
    messages: 'メッセージ',
    'kicks-mentioned-user': 'メンションされたユーザーをキック',
    'bans-mentioned-user': 'メンションされたユーザーをBAN',
    'voice-mutes-mentioned-user': 'メンションされたユーザーをボイスミュート',
    'requires-administrator': '管理者権限が必要',
    'requires-nsfw-channel': 'NSFWチャンネルが必要',
    'no-actions-configured': 'このコマンドにはアクションが設定されていません。'
  },
  zh: {
    'version-value': '1.4.0',
    'send-webhook': '发送Discord Webhook',
    'no-presets': '无预设',
    'webhook-url': 'Webhook URL',
    name: '名称',
    avatar: '头像URL',
    message: '消息',
    send: '发送',
    bot: '机器人',
    'message-placeholder': '在此输入消息',
    token: '令牌',
    login: '登录',
    logout: '登出',
    invite: '邀请',
    status: '状态',
    activity: '活动',
    'status-details': '状态详情',
    'status-details-placeholder': '在此输入状态详情',
    'twitch-url': 'Twitch.tv URL',
    'update-status': '更新状态',
    settings: '设置',
    theme: '主题',
    'show-token': '显示令牌',
    'show-token-description': '以明文显示API密钥和令牌，而非隐藏',
    'hide-output': '隐藏输出预览',
    'hide-output-description': '在编辑器中隐藏命令输出预览面板',
    language: '语言',
    about: '关于',
    'bot-state': '机器人状态',
    value: '值',
    'run-code': '运行代码',
    'run-code-placeholder': '在此输入JavaScript代码...',
    output: '输出',
    run: '运行',
    stats: '统计',
    users: '用户',
    'messages-sent': '已发送消息',
    'messages-received': '已接收消息',
    'on-join': '加入时',
    'on-leave': '离开时',
    'on-ban': '被禁时',
    'private-messages-received': '接收的私人消息',
    servers: '服务器',
    commands: '命令',
    'time-spent-in-app': '在应用中花费的时间',
    'webhooks-sent': '已发送的Webhook',
    cancel: '取消',
    'add-command': '添加命令',
    'no-commands-found': '未找到命令。',
    'no-commands': '无命令',
    'add-command-hint': '添加命令以开始',
    'command-exported-to-clipboard': '命令已导出到剪贴板！',
    'import-json-command': '导入JSON命令',
    delete: '删除',
    'are-you-sure-you-want-to-delete-the-command': '您确定要删除命令吗？',
    'tip-shift-click-delete': '提示：按住Shift键点击删除按钮可跳过此确认。',
    'open-quote': '"',
    'close-quote': '"',
    'edit-command': '编辑命令',
    'choose-command-type': '选择命令类型',
    'message-received': '收到消息',
    'private-message-received': '收到私人消息',
    'member-join': '成员加入',
    'member-leave': '成员离开',
    'member-ban': '成员被禁',
    reaction: '反应',
    'bot-login': '机器人登录',
    command: '命令',
    description: '描述',
    'reaction-placeholder': '表情符号ID或名称或😊',
    'specific-message-only': '仅特定消息',
    'message-id': '消息ID',
    phrase: '短语',
    'requires-role': '需要角色',
    'required-role': '所需角色',
    'role-id': '角色ID',
    'requires-admin': '需要管理员',
    'send-message': '发送消息',
    'channel-message': '频道消息',
    'as-reply': '作为回复',
    'send-channel-embed': '发送频道嵌入',
    'channel-embed-title': '频道嵌入标题',
    'channel-embed-description': '频道嵌入描述',
    'channel-embed-footer': '频道嵌入页脚',
    'channel-embed-image': '频道嵌入图片',
    'channel-embed-thumbnail': '频道嵌入缩略图',
    'channel-embed-color': '频道嵌入颜色',
    'send-in-specific-channel': '发送到特定频道',
    'specific-channel': '特定频道',
    'channel-whitelist': '频道白名单',
    'server-whitelist': '服务器白名单',
    'send-private-message': '发送私人消息',
    'private-message': '私人消息',
    'send-private-embed': '发送私人嵌入',
    'private-embed-title': '私人嵌入标题',
    'private-embed-description': '私人嵌入描述',
    'private-embed-footer': '私人嵌入页脚',
    'private-embed-image': '私人嵌入图片',
    'private-embed-thumbnail': '私人嵌入缩略图',
    'private-embed-color': '私人嵌入颜色',
    'react-to-message': '对消息做出反应',
    'ignore-error-message': '忽略错误消息',
    'delete-if-contains': '如果包含则删除',
    'delete-if-strings': '如果是字符串则删除',
    'delete-after': '之后删除',
    'delete-x-times': '删除X次',
    'delete-num': '删除数量',
    'is-nsfw': '是NSFW',
    cooldown: '冷却',
    'cooldown-type': '冷却类型',
    'cooldown-user': '用户',
    'cooldown-server': '服务器',
    'cooldown-global': '全局',
    'cooldown-message': '冷却消息',
    'cooldown-hint': '设置为0或留空以禁用。',
    moderation: '管理',
    kick: '踢出',
    ban: '禁止',
    'voice-mute': '语音静音',
    'role-assigner': '角色分配器',
    'role-to-assign': '要分配的角色',
    'update-command': '更新命令',
    action: '动作',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒',
    'status-online': '在线',
    'status-idle': '空闲',
    'status-dnd': '请勿打扰',
    'status-invisible': '隐身',
    'activity-playing': '玩',
    'activity-streaming': '直播',
    'activity-listening': '听',
    'activity-watching': '看',
    'activity-none': '无',
    'activity-competing': '竞争',
    'language-tooltip': '语言可能是机器翻译的。',
    'no-state-data': '没有状态数据。',
    help: '帮助',
    details: '详情',
    actions: '操作',
    'command-trigger': '命令触发器',
    'command-only': '仅命令',
    'starts-with': '以...开始',
    'startup-js': '启动JavaScript',
    save: '保存',
    'restart-js-engine': '重启JS引擎',
    export: '导出',
    import: '导入',
    general: '通用',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI API密钥',
    'enter-your-openai-api-key': '输入您的OpenAI API密钥...',
    'openai-model': 'OpenAI模型',
    'developer-prompt': '开发者提示',
    'enter-your-custom-developer-prompt': '输入您的自定义开发者提示...',
    'disable-reasoning-api': '禁用推理API',
    'disable-reasoning-api-description': '对思维模型（GPT-5.1、GPT-5.2）使用标准API而非流式推理API',
    advanced: '高级',
    'use-legacy-interpreter': '使用旧版解释器',
    'use-legacy-interpreter-description':
      '使用旧的基于正则表达式的模板解释器，而非新的基于AST的解释器',
    // AI Chat strings
    'ai-assistant': 'AI助手',
    'ai-chat-started': 'AI助手已准备好帮助编辑命令:',
    'proposed-changes': '建议的更改',
    changes: '更改',
    'accept-changes': '接受更改',
    reject: '拒绝',
    'changes-applied': '更改已成功应用',
    'changes-rejected': '更改已拒绝',
    'describe-changes': '描述您想要更改的内容...',
    'api-key-needed': '需要OpenAI API密钥',
    'openai-key-required': '请在设置中添加您的OpenAI API密钥以使用AI助手。',
    'select-model': '选择AI模型',
    'select-context': '选择上下文',
    'total-tokens': '总Token使用量',
    'new-chat': '新对话',
    'clear-chat': '清除对话',
    close: '关闭',
    'suggest-improvements': '建议改进',
    'make-funnier': '更有趣',
    'add-randomness': '添加随机性',
    'use-mentions': '使用提及',
    'add-counter': '添加计数器',
    'quick-suggest-improvements': '分析此命令并提出改进建议，使其更有效、用户友好或功能丰富',
    'quick-make-funnier': '使此命令响应更有趣和吸引人',
    'quick-add-random': '使用$random{}为响应添加随机变化',
    'quick-add-mentions': '在响应中包含用户提及，如$name和$botName',
    'quick-add-counter': '使用$eval和botState添加计数器来跟踪命令使用情况',
    // Interaction Commands
    interactions: '交互',
    'add-interaction': '添加交互',
    'edit-interaction': '编辑交互',
    'no-interactions-found': '未找到交互。',
    'no-interactions': '无交互',
    'add-interaction-hint': '添加交互以开始',
    'sync-all': '全部同步',
    registered: '已注册',
    'not-registered': '未注册',
    unregister: '取消注册',
    options: '选项',
    buttons: '按钮',
    edit: '编辑',
    'edit-json-value': '编辑JSON值',
    'confirm-delete': '确认删除',
    'confirm-delete-variable': '您确定要删除该变量吗',
    'delete-interaction-confirm': '您确定要删除该交互吗',
    'command-details': '命令详情',
    'command-name': '命令名称',
    'command-name-hint': '小写，无空格。使用字母、数字、连字符、下划线。',
    'command-description': '命令描述',
    'command-options': '命令选项',
    'add-option': '添加选项',
    'no-options-hint': '无选项。添加选项以允许用户为您的命令提供输入。',
    'option-name': '选项名称',
    'option-type': '选项类型',
    'option-required': '必填',
    required: '必填',
    'option-description': '选项描述',
    'root-action': '命令响应',
    'root-action-hint': '使用斜杠命令时发生的情况。',
    'add-button': '添加按钮',
    'no-buttons-hint': '无按钮。添加按钮以创建交互式响应。',
    'max-buttons-warning': '每行最多5个按钮。Discord限制每个操作行5个按钮。',
    'response-buttons': '响应按钮',
    'no-response-buttons-hint': '添加按钮以附加到此响应。',
    'nesting-level': '级别',
    'button-label': '按钮标签',
    'button-style': '按钮样式',
    'button-custom-id': '自定义ID',
    'button-emoji': '表情符号',
    'button-url': 'URL',
    'button-disabled': '已禁用',
    'button-action': '按钮操作',
    'style-primary': '主要',
    'style-secondary': '次要',
    'style-success': '成功',
    'style-danger': '危险',
    'style-link': '链接',
    ephemeral: '临时（仅用户可见）',
    'defer-reply': '延迟回复（用于慢速操作）',
    'add-action': '添加操作',
    'all-actions-added': '已添加所有操作',
    'interaction-send-channel-message': '发送频道消息',
    'interaction-send-channel-embed': '发送频道嵌入',
    'embed-title': '标题',
    'embed-description': '描述',
    'embed-color': '颜色（十六进制）',
    'embed-image': '图片URL',
    'embed-thumbnail': '缩略图URL',
    'embed-footer': '页脚',
    disabled: '已禁用',
    search: '搜索',
    // Validation messages
    'fix-errors-to-save': '修复错误以保存',
    'description-required': '描述是必填项',
    'command-required': '命令是必填项',
    'message-is-required': '消息是必填项',
    'embed-field-required': '至少需要一个嵌入字段',
    'channel-id-required': '需要频道ID',
    'channel-ids-required': '需要频道ID',
    'server-ids-required': '需要服务器ID',
    'reaction-required': '需要反应',
    'delete-strings-required': '需要删除字符串',
    'delete-number-required': '删除数量必须至少为1',
    'role-id-is-required': '需要角色ID',
    'name-is-required': '名称是必填项',
    'name-invalid-format': '必须为1-32个字符，可使用字母、数字、连字符、下划线或撇号',
    'description-too-long': '描述必须为1-100个字符',
    'duplicate-option-name': '选项名称重复',
    'no-actions-added-hint': '未添加操作。请至少添加一个操作。',
    'action-incompatible-with-type': '此操作对所选事件类型无效',
    'send-channel-message': '发送频道消息',
    // API Auth strings
    account: '账户',
    'sign-in': '登录',
    'sign-out': '退出登录',
    'signed-in-as': '已登录为',
    username: '用户名',
    password: '密码',
    register: '注册',
    'need-account': '没有账户？注册',
    'have-account': '已有账户？登录',
    // Onboarding and tips
    'got-it': '知道了',
    'onboarding-getting-started': '开始使用',
    'onboarding-enter-token-message': '访问 Discord 开发者门户，创建机器人并复制其令牌。',
    'onboarding-open-portal': '打开门户',
    'onboarding-create-command-message': '创建一个命令，让您的机器人有事可做。',
    'onboarding-go-to-commands': '前往命令',
    'onboarding-host-bot-message': '按登录让您的机器人上线！',
    webhooks: 'Webhooks',
    debugger: '调试器',
    'tip-commands-body':
      '命令定义机器人如何响应消息。创建一个命令，设置触发词，然后添加发送消息等操作。',
    'tip-webhooks-body':
      '无需托管机器人即可向 Discord 频道发送消息。请从 Discord 服务器设置中粘贴 webhook URL。',
    'tip-interactions-body':
      '交互是 Discord 斜杠命令。创建一个交互，然后点击同步将其注册到 Discord。',
    'tip-debugger-body':
      '机器人状态会显示命令中的持久变量。控制台可让您针对机器人上下文测试 JavaScript 片段。',
    // Command Repository strings
    'command-repository': '命令仓库',
    newest: '最新',
    'most-downloaded': '最多下载',
    browse: '浏览',
    'my-shared-commands': '我分享的命令',
    'search-commands': '搜索命令...',
    dismiss: '关闭',
    'no-commands-in-repository': '仓库中没有找到命令。',
    'try-different-search': '尝试其他搜索词。',
    preview: '预览',
    downloads: '下载',
    'no-shared-commands': '您还没有分享任何命令。',
    'share-commands-hint': '从命令编辑器分享命令后，它们将显示在这里。',
    'confirm-delete-shared-command': '您确定要从仓库中删除此命令吗？',
    'delete-command-failed': '删除命令失败',
    'import-command-failed': '导入命令失败',
    'browse-repository': '浏览仓库',
    // Share Command Modal strings
    share: '分享',
    'share-command': '分享命令',
    'command-shared-successfully': '命令分享成功！',
    type: '类型',
    trigger: '触发器',
    'share-info': '您的命令将在仓库中公开，供其他人导入。',
    'no-command-selected': '未选择命令。',
    // Command Preview Modal strings
    'command-preview': '命令预览',
    'no-embed-configured': '未配置嵌入',
    'channel-id': '频道ID',
    'deletes-command-message': '发送后删除命令消息',
    messages: '条消息',
    'kicks-mentioned-user': '踢出被提及的用户',
    'bans-mentioned-user': '封禁被提及的用户',
    'voice-mutes-mentioned-user': '语音静音被提及的用户',
    'requires-administrator': '需要管理员权限',
    'requires-nsfw-channel': '需要NSFW频道',
    'no-actions-configured': '此命令没有配置任何操作。'
  },
  ko: {
    'version-value': '1.4.0',
    'send-webhook': 'Discord Webhook 보내기',
    'no-presets': '프리셋 없음',
    'webhook-url': 'Webhook URL',
    name: '이름',
    avatar: '아바타 URL',
    message: '메시지',
    send: '보내기',
    bot: '봇',
    'message-placeholder': '여기에 메시지를 입력하세요',
    token: '토큰',
    login: '로그인',
    logout: '로그아웃',
    invite: '초대',
    status: '상태',
    activity: '활동',
    'status-details': '상태 세부 정보',
    'status-details-placeholder': '여기에 상태 세부 정보를 입력하세요',
    'twitch-url': 'Twitch.tv URL',
    'update-status': '상태 업데이트',
    settings: '설정',
    theme: '테마',
    'show-token': '토큰 표시',
    'show-token-description': 'API 키와 토큰을 숨기지 않고 일반 텍스트로 표시',
    'hide-output': '출력 미리보기 숨기기',
    'hide-output-description': '에디터에서 명령 출력 미리보기 패널 숨기기',
    language: '언어',
    about: '정보',
    'bot-state': '봇 상태',
    value: '값',
    'run-code': '코드 실행',
    'run-code-placeholder': '여기에 JavaScript 코드를 입력하세요...',
    output: '출력',
    run: '실행',
    stats: '통계',
    users: '사용자',
    'messages-sent': '보낸 메시지',
    'messages-received': '받은 메시지',
    'on-join': '참여 시',
    'on-leave': '떠날 때',
    'on-ban': '차단 시',
    'private-messages-received': '받은 개인 메시지',
    servers: '서버',
    commands: '명령어',
    'time-spent-in-app': '앱에서 보낸 시간',
    'webhooks-sent': '보낸 Webhook',
    cancel: '취소',
    'add-command': '명령어 추가',
    'no-commands-found': '명령어를 찾을 수 없습니다.',
    'no-commands': '명령어 없음',
    'add-command-hint': '명령어를 추가하여 시작하세요',
    'command-exported-to-clipboard': '명령어가 클립보드에 내보내졌습니다!',
    'import-json-command': 'JSON 명령어 가져오기',
    delete: '삭제',
    'are-you-sure-you-want-to-delete-the-command': '명령어를 삭제하시겠습니까?',
    'tip-shift-click-delete':
      '팁: Shift 키를 누른 채 삭제 버튼을 클릭하면 이 확인을 건너뛸 수 있습니다.',
    'open-quote': '"',
    'close-quote': '"',
    'edit-command': '명령어 편집',
    'choose-command-type': '명령어 유형 선택',
    'message-received': '메시지 수신',
    'private-message-received': '개인 메시지 수신',
    'member-join': '회원 가입',
    'member-leave': '회원 탈퇴',
    'member-ban': '회원 차단',
    reaction: '반응',
    'bot-login': '봇 로그인',
    command: '명령어',
    description: '설명',
    'reaction-placeholder': '이모지 ID 또는 이름 또는 😊',
    'specific-message-only': '특정 메시지만',
    'message-id': '메시지 ID',
    phrase: '구문',
    'requires-role': '역할 필요',
    'required-role': '필요한 역할',
    'role-id': '역할 ID',
    'requires-admin': '관리자 필요',
    'send-message': '메시지 보내기',
    'channel-message': '채널 메시지',
    'as-reply': '답장으로',
    'send-channel-embed': '채널 임베드 보내기',
    'channel-embed-title': '채널 임베드 제목',
    'channel-embed-description': '채널 임베드 설명',
    'channel-embed-footer': '채널 임베드 바닥글',
    'channel-embed-image': '채널 임베드 이미지',
    'channel-embed-thumbnail': '채널 임베드 썸네일',
    'channel-embed-color': '채널 임베드 색상',
    'send-in-specific-channel': '특정 채널에 전송',
    'specific-channel': '특정 채널',
    'channel-whitelist': '채널 화이트리스트',
    'server-whitelist': '서버 화이트리스트',
    'send-private-message': '개인 메시지 보내기',
    'private-message': '개인 메시지',
    'send-private-embed': '개인 임베드 보내기',
    'private-embed-title': '개인 임베드 제목',
    'private-embed-description': '개인 임베드 설명',
    'private-embed-footer': '개인 임베드 바닥글',
    'private-embed-image': '개인 임베드 이미지',
    'private-embed-thumbnail': '개인 임베드 썸네일',
    'private-embed-color': '개인 임베드 색상',
    'react-to-message': '메시지에 반응',
    'ignore-error-message': '오류 메시지 무시',
    'delete-if-contains': '포함 시 삭제',
    'delete-if-strings': '문자열 시 삭제',
    'delete-after': '후에 삭제',
    'delete-x-times': 'X번 삭제',
    'delete-num': '삭제 수',
    'is-nsfw': 'NSFW입니다',
    cooldown: '쿨다운',
    'cooldown-type': '쿨다운 유형',
    'cooldown-user': '사용자',
    'cooldown-server': '서버',
    'cooldown-global': '글로벌',
    'cooldown-message': '쿨다운 메시지',
    'cooldown-hint': '0으로 설정하거나 비워두면 비활성화됩니다.',
    moderation: '관리',
    kick: '추방',
    ban: '차단',
    'voice-mute': '음성 음소거',
    'role-assigner': '역할 할당자',
    'role-to-assign': '할당할 역할',
    'update-command': '명령어 업데이트',
    action: '동작',
    hours: '시간',
    minutes: '분',
    seconds: '초',
    'status-online': '온라인',
    'status-idle': '아이들',
    'status-dnd': '노키즈 디스트럭트',
    'status-invisible': '인비저블',
    'activity-playing': '플레이',
    'activity-streaming': '스트리밍',
    'activity-listening': '리스닝',
    'activity-watching': '워치',
    'activity-none': '노',
    'activity-competing': '경쟁',
    'language-tooltip': '언어는 자동 번역일 수 있습니다.',
    'no-state-data': '상태 데이터가 없습니다.',
    help: '도움말',
    details: '세부 정보',
    actions: '작업',
    'command-trigger': '명령 트리거',
    'command-only': '명령만',
    'starts-with': '시작',
    'startup-js': '시작 JavaScript',
    save: '저장',
    'restart-js-engine': 'JS 엔진 재시작',
    export: '내보내기',
    import: '가져오기',
    general: '일반',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI API 키',
    'enter-your-openai-api-key': 'OpenAI API 키를 입력하세요...',
    'openai-model': 'OpenAI 모델',
    'developer-prompt': '개발자 프롬프트',
    'enter-your-custom-developer-prompt': '사용자 정의 개발자 프롬프트를 입력하세요...',
    'disable-reasoning-api': '추론 API 비활성화',
    'disable-reasoning-api-description':
      '사고 모델(GPT-5.1, GPT-5.2)에 스트리밍 추론 API 대신 표준 API 사용',
    advanced: '고급',
    'use-legacy-interpreter': '레거시 인터프리터 사용',
    'use-legacy-interpreter-description':
      '새로운 AST 기반 대신 이전 정규식 기반 템플릿 인터프리터 사용',
    // AI Chat strings
    'ai-assistant': 'AI 어시스턴트',
    'ai-chat-started': 'AI 어시스턴트가 명령 편집 준비 완료:',
    'proposed-changes': '제안된 변경 사항',
    changes: '변경',
    'accept-changes': '변경 수락',
    reject: '거부',
    'changes-applied': '변경 사항이 성공적으로 적용되었습니다',
    'changes-rejected': '변경 사항이 거부되었습니다',
    'describe-changes': '변경하고 싶은 내용을 설명하세요...',
    'api-key-needed': 'OpenAI API 키가 필요합니다',
    'openai-key-required': 'AI 어시스턴트를 사용하려면 설정에서 OpenAI API 키를 추가하세요.',
    'select-model': 'AI 모델 선택',
    'select-context': '컨텍스트 선택',
    'total-tokens': '총 토큰 사용량',
    'new-chat': '새 채팅',
    'clear-chat': '채팅 지우기',
    close: '닫기',
    'suggest-improvements': '개선 사항 제안',
    'make-funnier': '더 재미있게',
    'add-randomness': '무작위성 추가',
    'use-mentions': '멘션 사용',
    'add-counter': '카운터 추가',
    'quick-suggest-improvements':
      '이 명령을 분석하고 더 효과적이고 사용자 친화적이며 풍부한 기능을 갖추도록 개선 사항을 제안하세요',
    'quick-make-funnier': '이 명령 응답을 더 재미있고 매력적으로 만들기',
    'quick-add-random': '$random{}을 사용하여 응답에 무작위 변형 추가',
    'quick-add-mentions': '$name 및 $botName과 같은 사용자 멘션을 응답에 포함',
    'quick-add-counter': '$eval 및 botState를 사용하여 명령 사용량을 추적하는 카운터 추가',
    // Interaction Commands
    interactions: '인터랙션',
    'add-interaction': '인터랙션 추가',
    'edit-interaction': '인터랙션 편집',
    'no-interactions-found': '인터랙션을 찾을 수 없습니다.',
    'no-interactions': '인터랙션 없음',
    'add-interaction-hint': '인터랙션을 추가하여 시작하세요',
    'sync-all': '모두 동기화',
    registered: '등록됨',
    'not-registered': '미등록',
    unregister: '등록 취소',
    options: '옵션',
    buttons: '버튼',
    edit: '편집',
    'edit-json-value': 'JSON 값 편집',
    'confirm-delete': '삭제 확인',
    'confirm-delete-variable': '이 변수를 삭제하시겠습니까',
    'delete-interaction-confirm': '이 인터랙션을 삭제하시겠습니까',
    'command-details': '명령어 세부 정보',
    'command-name': '명령어 이름',
    'command-name-hint': '소문자, 공백 없음. 문자, 숫자, 하이픈, 밑줄을 사용하세요.',
    'command-description': '명령어 설명',
    'command-options': '명령어 옵션',
    'add-option': '옵션 추가',
    'no-options-hint':
      '옵션이 없습니다. 사용자가 명령어에 입력을 제공할 수 있도록 옵션을 추가하세요.',
    'option-name': '옵션 이름',
    'option-type': '옵션 유형',
    'option-required': '필수',
    required: '필수',
    'option-description': '옵션 설명',
    'root-action': '명령어 응답',
    'root-action-hint': '슬래시 명령어가 사용될 때 발생하는 동작.',
    'add-button': '버튼 추가',
    'no-buttons-hint': '버튼이 없습니다. 버튼을 추가하여 인터랙티브 응답을 만드세요.',
    'max-buttons-warning': '행당 최대 5개 버튼. Discord는 액션 행당 5개 버튼으로 제한합니다.',
    'response-buttons': '응답 버튼',
    'no-response-buttons-hint': '이 응답에 첨부할 버튼을 추가하세요.',
    'nesting-level': '레벨',
    'button-label': '버튼 라벨',
    'button-style': '버튼 스타일',
    'button-custom-id': '커스텀 ID',
    'button-emoji': '이모지',
    'button-url': 'URL',
    'button-disabled': '비활성화됨',
    'button-action': '버튼 액션',
    'style-primary': '기본',
    'style-secondary': '보조',
    'style-success': '성공',
    'style-danger': '위험',
    'style-link': '링크',
    ephemeral: '임시 (사용자에게만 표시)',
    'defer-reply': '응답 지연 (느린 작업용)',
    'add-action': '액션 추가',
    'all-actions-added': '모든 액션이 추가되었습니다',
    'interaction-send-channel-message': '채널 메시지 보내기',
    'interaction-send-channel-embed': '채널 임베드 보내기',
    'embed-title': '제목',
    'embed-description': '설명',
    'embed-color': '색상 (16진수)',
    'embed-image': '이미지 URL',
    'embed-thumbnail': '썸네일 URL',
    'embed-footer': '바닥글',
    disabled: '비활성화됨',
    search: '검색',
    // Validation messages
    'fix-errors-to-save': '저장하려면 오류를 수정하세요',
    'description-required': '설명은 필수입니다',
    'command-required': '명령어는 필수입니다',
    'message-is-required': '메시지는 필수입니다',
    'embed-field-required': '최소 하나의 임베드 필드가 필요합니다',
    'channel-id-required': '채널 ID가 필요합니다',
    'channel-ids-required': '채널 ID가 필요합니다',
    'server-ids-required': '서버 ID가 필요합니다',
    'reaction-required': '반응이 필요합니다',
    'delete-strings-required': '삭제 문자열이 필요합니다',
    'delete-number-required': '삭제 수는 최소 1이어야 합니다',
    'role-id-is-required': '역할 ID가 필요합니다',
    'name-is-required': '이름은 필수입니다',
    'name-invalid-format': '1-32자의 문자, 숫자, 하이픈, 밑줄 또는 아포스트로피를 사용하세요',
    'description-too-long': '설명은 1-100자여야 합니다',
    'duplicate-option-name': '중복된 옵션 이름',
    'no-actions-added-hint': '액션이 추가되지 않았습니다. 최소 하나의 액션을 추가하세요.',
    'action-incompatible-with-type': '이 액션은 선택한 이벤트 유형에 효과가 없습니다',
    'send-channel-message': '채널 메시지 보내기',
    // API Auth strings
    account: '계정',
    'sign-in': '로그인',
    'sign-out': '로그아웃',
    'signed-in-as': '로그인됨',
    username: '사용자 이름',
    password: '비밀번호',
    register: '가입하기',
    'need-account': '계정이 없으신가요? 가입하기',
    'have-account': '이미 계정이 있으신가요? 로그인',
    // Onboarding and tips
    'got-it': '확인',
    'onboarding-getting-started': '시작하기',
    'onboarding-enter-token-message': 'Discord Developer Portal에서 봇을 만들고 토큰을 복사하세요.',
    'onboarding-open-portal': '포털 열기',
    'onboarding-create-command-message': '봇이 할 일을 만들 수 있도록 명령어를 생성하세요.',
    'onboarding-go-to-commands': '명령어로 이동',
    'onboarding-host-bot-message': '로그인을 눌러 봇을 온라인으로 전환하세요!',
    webhooks: 'Webhooks',
    debugger: '디버거',
    'tip-commands-body':
      '명령어는 봇이 메시지에 응답하는 방식을 정의합니다. 명령어를 만들고 트리거 단어를 설정한 다음 메시지 보내기 같은 작업을 추가하세요.',
    'tip-webhooks-body':
      '봇을 호스팅하지 않고 Discord 채널에 메시지를 보낼 수 있습니다. Discord 서버 설정의 webhook URL을 붙여넣으세요.',
    'tip-interactions-body':
      '인터랙션은 Discord 슬래시 명령어입니다. 하나를 만든 다음 동기화를 눌러 Discord에 등록하세요.',
    'tip-debugger-body':
      '봇 상태는 명령어의 영구 변수를 보여줍니다. 콘솔에서는 봇 컨텍스트에서 JavaScript 스니펫을 테스트할 수 있습니다.',
    // Command Repository strings
    'command-repository': '명령어 저장소',
    newest: '최신',
    'most-downloaded': '인기순',
    browse: '둘러보기',
    'my-shared-commands': '내가 공유한 명령어',
    'search-commands': '명령어 검색...',
    dismiss: '닫기',
    'no-commands-in-repository': '저장소에서 명령어를 찾을 수 없습니다.',
    'try-different-search': '다른 검색어를 시도해 보세요.',
    preview: '미리보기',
    downloads: '다운로드',
    'no-shared-commands': '아직 공유한 명령어가 없습니다.',
    'share-commands-hint': '명령어 편집기에서 명령어를 공유하면 여기에 표시됩니다.',
    'confirm-delete-shared-command': '이 명령어를 저장소에서 삭제하시겠습니까?',
    'delete-command-failed': '명령어 삭제 실패',
    'import-command-failed': '명령어 가져오기 실패',
    'browse-repository': '저장소 둘러보기',
    // Share Command Modal strings
    share: '공유',
    'share-command': '명령어 공유',
    'command-shared-successfully': '명령어가 성공적으로 공유되었습니다!',
    type: '유형',
    trigger: '트리거',
    'share-info': '명령어가 저장소에 공개되어 다른 사용자가 가져올 수 있습니다.',
    'no-command-selected': '선택된 명령어가 없습니다.',
    // Command Preview Modal strings
    'command-preview': '명령어 미리보기',
    'no-embed-configured': '임베드가 설정되지 않음',
    'channel-id': '채널 ID',
    'deletes-command-message': '전송 후 명령어 메시지 삭제',
    messages: '개의 메시지',
    'kicks-mentioned-user': '언급된 사용자 추방',
    'bans-mentioned-user': '언급된 사용자 차단',
    'voice-mutes-mentioned-user': '언급된 사용자 음성 음소거',
    'requires-administrator': '관리자 역할 필요',
    'requires-nsfw-channel': 'NSFW 채널 필요',
    'no-actions-configured': '이 명령어에 구성된 작업이 없습니다.'
  },
  ru: {
    'version-value': '1.4.0',
    'send-webhook': 'Отправить Discord Webhook',
    'no-presets': 'Нет пресетов',
    'webhook-url': 'URL вебхука',
    name: 'Имя',
    avatar: 'URL аватара',
    message: 'Сообщение',
    send: 'Отправить',
    bot: 'Бот',
    'message-placeholder': 'Введите ваше сообщение здесь',
    token: 'Токен',
    login: 'Войти',
    logout: 'Выйти',
    invite: 'Пригласить',
    status: 'Статус',
    activity: 'Активность',
    'status-details': 'Детали статуса',
    'status-details-placeholder': 'Введите детали вашего статуса здесь',
    'twitch-url': 'URL Twitch.tv',
    'update-status': 'Обновить статус',
    settings: 'Настройки',
    theme: 'Тема',
    'show-token': 'Показать токен',
    'show-token-description': 'Отображать API-ключи и токены открытым текстом вместо скрытых',
    'hide-output': 'Скрыть предпросмотр вывода',
    'hide-output-description': 'Скрыть панель предпросмотра вывода команды в редакторе',
    language: 'Язык',
    about: 'О программе',
    'bot-state': 'Состояние бота',
    value: 'Значение',
    'run-code': 'Запустить код',
    'run-code-placeholder': 'Введите JavaScript код здесь...',
    output: 'Вывод',
    run: 'Запустить',
    stats: 'Статистика',
    users: 'Пользователи',
    'messages-sent': 'Отправлено сообщений',
    'messages-received': 'Получено сообщений',
    'on-join': 'При присоединении',
    'on-leave': 'При выходе',
    'on-ban': 'При бане',
    'private-messages-received': 'Получено личных сообщений',
    servers: 'Серверы',
    commands: 'Команды',
    'time-spent-in-app': 'Время в приложении',
    'webhooks-sent': 'Отправлено вебхуков',
    cancel: 'Отмена',
    'add-command': 'Добавить команду',
    'no-commands-found': 'Команды не найдены.',
    'no-commands': 'Нет команд',
    'add-command-hint': 'Добавьте команду для начала',
    'command-exported-to-clipboard': 'Команда экспортирована в буфер обмена!',
    'import-json-command': 'Импортировать JSON-команду',
    delete: 'Удалить',
    'are-you-sure-you-want-to-delete-the-command': 'Вы уверены, что хотите удалить команду?',
    'tip-shift-click-delete':
      'Совет: удерживайте Shift и нажмите кнопку удаления, чтобы пропустить это подтверждение.',
    'open-quote': '«',
    'close-quote': '»',
    'edit-command': 'Редактировать команду',
    'choose-command-type': 'Выберите тип команды',
    'message-received': 'Сообщение получено',
    'private-message-received': 'Личное сообщение получено',
    'member-join': 'Участник присоединился',
    'member-leave': 'Участник покинул',
    'member-ban': 'Участник забанен',
    reaction: 'Реакция',
    'bot-login': 'Вход бота',
    command: 'Команда',
    description: 'Описание',
    'reaction-placeholder': 'ID или имя эмодзи или 😊',
    'specific-message-only': 'Только конкретное сообщение',
    'message-id': 'ID сообщения',
    phrase: 'Фраза',
    'requires-role': 'Требуется роль',
    'required-role': 'Требуемая роль',
    'role-id': 'ID роли',
    'requires-admin': 'Требуется администратор',
    'send-message': 'Отправить сообщение',
    'channel-message': 'Сообщение канала',
    'as-reply': 'Как ответ',
    'send-channel-embed': 'Отправить встраивание канала',
    'channel-embed-title': 'Заголовок встраивания канала',
    'channel-embed-description': 'Описание встраивания канала',
    'channel-embed-footer': 'Нижний колонтитул встраивания канала',
    'channel-embed-image': 'Изображение встраивания канала',
    'channel-embed-thumbnail': 'Миниатюра встраивания канала',
    'channel-embed-color': 'Цвет встраивания канала',
    'send-in-specific-channel': 'Отправить в конкретный канал',
    'specific-channel': 'Конкретный канал',
    'channel-whitelist': 'Белый список каналов',
    'server-whitelist': 'Белый список серверов',
    'send-private-message': 'Отправить личное сообщение',
    'private-message': 'Личное сообщение',
    'send-private-embed': 'Отправить личное встраивание',
    'private-embed-title': 'Заголовок личного встраивания',
    'private-embed-description': 'Описание личного встраивания',
    'private-embed-footer': 'Нижний колонтитул личного встраивания',
    'private-embed-image': 'Изображение личного встраивания',
    'private-embed-thumbnail': 'Миниатюра личного встраивания',
    'private-embed-color': 'Цвет личного встраивания',
    'react-to-message': 'Реагировать на сообщение',
    'ignore-error-message': 'Игнорировать сообщение об ошибке',
    'delete-if-contains': 'Удалить, если содержит',
    'delete-if-strings': 'Удалить, если строки',
    'delete-after': 'Удалить после',
    'delete-x-times': 'Удалить X раз',
    'delete-num': 'Удалить количество',
    'is-nsfw': 'Это NSFW',
    cooldown: 'Кулдаун',
    'cooldown-type': 'Тип кулдауна',
    'cooldown-user': 'Пользователь',
    'cooldown-server': 'Сервер',
    'cooldown-global': 'Глобальный',
    'cooldown-message': 'Сообщение кулдауна',
    'cooldown-hint': 'Установите 0 или оставьте пустым для отключения.',
    moderation: 'Модерация',
    kick: 'Кик',
    ban: 'Бан',
    'voice-mute': 'Отключить голос',
    'role-assigner': 'Назначение роли',
    'role-to-assign': 'Роль для назначения',
    'update-command': 'Обновить команду',
    action: 'Действие',
    hours: 'ч',
    minutes: 'мин',
    seconds: 'с',
    'status-online': 'Онлайн',
    'status-idle': 'Игра',
    'status-dnd': 'Не беспокоить',
    'status-invisible': 'Невидимый',
    'activity-playing': 'Игра',
    'activity-streaming': 'Стрим',
    'activity-listening': 'Слушать',
    'activity-watching': 'Смотреть',
    'activity-none': 'Ничего',
    'activity-competing': 'Соревнование',
    'language-tooltip': 'Язык может быть машинным переводом.',
    'no-state-data': 'Нет данных о состоянии.',
    help: 'Помощь',
    details: 'Подробности',
    actions: 'Действия',
    'command-trigger': 'Триггер команды',
    'command-only': 'Только команда',
    'starts-with': 'Начинается с',
    'startup-js': 'Запуск JavaScript',
    save: 'Сохранить',
    'restart-js-engine': 'Перезапустить JS-движок',
    export: 'Экспорт',
    import: 'Импорт',
    general: 'Общие',
    openai: 'OpenAI',
    'openai-api-key': 'API-ключ OpenAI',
    'enter-your-openai-api-key': 'Введите ваш API-ключ OpenAI...',
    'openai-model': 'Модель OpenAI',
    'developer-prompt': 'Запрос разработчика',
    'enter-your-custom-developer-prompt': 'Введите свой пользовательский запрос разработчика...',
    'disable-reasoning-api': 'Отключить API рассуждений',
    'disable-reasoning-api-description':
      'Использовать стандартный API вместо потокового API рассуждений для мыслящих моделей (GPT-5.1, GPT-5.2)',
    advanced: 'Дополнительно',
    'use-legacy-interpreter': 'Использовать старый интерпретатор',
    'use-legacy-interpreter-description':
      'Использовать старый интерпретатор шаблонов на основе regex вместо нового на основе AST',
    // AI Chat strings
    'ai-assistant': 'ИИ Ассистент',
    'ai-chat-started': 'ИИ ассистент готов помочь отредактировать команду:',
    'proposed-changes': 'Предлагаемые изменения',
    changes: 'изменения',
    'accept-changes': 'Принять изменения',
    reject: 'Отклонить',
    'changes-applied': 'Изменения успешно применены',
    'changes-rejected': 'Изменения отклонены',
    'describe-changes': 'Опишите, что вы хотите изменить...',
    'api-key-needed': 'Требуется API-ключ OpenAI',
    'openai-key-required':
      'Пожалуйста, добавьте ваш API-ключ OpenAI в настройках для использования ИИ ассистента.',
    'select-model': 'Выберите модель ИИ',
    'select-context': 'Выберите контекст',
    'total-tokens': 'Всего использовано токенов',
    'new-chat': 'Новый чат',
    'clear-chat': 'Очистить чат',
    close: 'Закрыть',
    'suggest-improvements': 'Предложить улучшения',
    'make-funnier': 'Сделать смешнее',
    'add-randomness': 'Добавить случайность',
    'use-mentions': 'Использовать упоминания',
    'add-counter': 'Добавить счётчик',
    'quick-suggest-improvements':
      'Проанализируйте эту команду и предложите улучшения, чтобы сделать её более эффективной, удобной для пользователя или функциональной',
    'quick-make-funnier': 'Сделать этот ответ команды смешнее и увлекательнее',
    'quick-add-random': 'Добавить случайные вариации в ответ с помощью $random{}',
    'quick-add-mentions': 'Включить упоминания пользователей, такие как $name и $botName, в ответ',
    'quick-add-counter':
      'Добавить счётчик с использованием $eval и botState для отслеживания использования команды',
    // Interaction Commands
    interactions: 'Взаимодействия',
    'add-interaction': 'Добавить взаимодействие',
    'edit-interaction': 'Редактировать взаимодействие',
    'no-interactions-found': 'Взаимодействия не найдены.',
    'no-interactions': 'Нет взаимодействий',
    'add-interaction-hint': 'Добавьте взаимодействие для начала',
    'sync-all': 'Синхронизировать всё',
    registered: 'Зарегистрировано',
    'not-registered': 'Не зарегистрировано',
    unregister: 'Отменить регистрацию',
    options: 'Параметры',
    buttons: 'Кнопки',
    edit: 'Редактировать',
    'edit-json-value': 'Редактировать JSON-значение',
    'confirm-delete': 'Подтвердить удаление',
    'confirm-delete-variable': 'Вы уверены, что хотите удалить переменную',
    'delete-interaction-confirm': 'Вы уверены, что хотите удалить взаимодействие',
    'command-details': 'Детали команды',
    'command-name': 'Имя команды',
    'command-name-hint':
      'Строчные буквы, без пробелов. Используйте буквы, цифры, дефисы, подчёркивания.',
    'command-description': 'Описание команды',
    'command-options': 'Параметры команды',
    'add-option': 'Добавить параметр',
    'no-options-hint':
      'Нет параметров. Добавьте параметры, чтобы пользователи могли вводить данные.',
    'option-name': 'Имя параметра',
    'option-type': 'Тип параметра',
    'option-required': 'Обязательный',
    required: 'Обязательный',
    'option-description': 'Описание параметра',
    'root-action': 'Ответ команды',
    'root-action-hint': 'Что происходит при использовании слэш-команды.',
    'add-button': 'Добавить кнопку',
    'no-buttons-hint': 'Нет кнопок. Добавьте кнопки для создания интерактивных ответов.',
    'max-buttons-warning':
      'Максимум 5 кнопок в ряд. Discord ограничивает кнопки до 5 на ряд действий.',
    'response-buttons': 'Кнопки ответа',
    'no-response-buttons-hint': 'Добавьте кнопки для прикрепления к этому ответу.',
    'nesting-level': 'Уровень',
    'button-label': 'Метка кнопки',
    'button-style': 'Стиль кнопки',
    'button-custom-id': 'Пользовательский ID',
    'button-emoji': 'Эмодзи',
    'button-url': 'URL',
    'button-disabled': 'Отключено',
    'button-action': 'Действие кнопки',
    'style-primary': 'Основной',
    'style-secondary': 'Вторичный',
    'style-success': 'Успех',
    'style-danger': 'Опасность',
    'style-link': 'Ссылка',
    ephemeral: 'Эфемерное (видно только пользователю)',
    'defer-reply': 'Отложенный ответ (для медленных действий)',
    'add-action': 'Добавить действие',
    'all-actions-added': 'Все действия добавлены',
    'interaction-send-channel-message': 'Отправить сообщение в канал',
    'interaction-send-channel-embed': 'Отправить встраивание в канал',
    'embed-title': 'Заголовок',
    'embed-description': 'Описание',
    'embed-color': 'Цвет (hex)',
    'embed-image': 'URL изображения',
    'embed-thumbnail': 'URL миниатюры',
    'embed-footer': 'Нижний колонтитул',
    disabled: 'Отключено',
    search: 'Поиск',
    // Validation messages
    'fix-errors-to-save': 'Исправьте ошибки для сохранения',
    'description-required': 'Описание обязательно',
    'command-required': 'Команда обязательна',
    'message-is-required': 'Сообщение обязательно',
    'embed-field-required': 'Требуется хотя бы одно поле встраивания',
    'channel-id-required': 'Требуется ID канала',
    'channel-ids-required': 'Требуются ID каналов',
    'server-ids-required': 'Требуются ID серверов',
    'reaction-required': 'Требуется реакция',
    'delete-strings-required': 'Требуются строки для удаления',
    'delete-number-required': 'Число удалений должно быть не менее 1',
    'role-id-is-required': 'Требуется ID роли',
    'name-is-required': 'Имя обязательно',
    'name-invalid-format':
      'Должно быть 1-32 символа с буквами, цифрами, дефисами, подчёркиваниями или апострофами',
    'description-too-long': 'Описание должно быть 1-100 символов',
    'duplicate-option-name': 'Дублирующееся имя параметра',
    'no-actions-added-hint': 'Действия не добавлены. Добавьте хотя бы одно действие.',
    'action-incompatible-with-type': 'Это действие не имеет эффекта для выбранного типа события',
    'send-channel-message': 'Отправить сообщение в канал',
    // API Auth strings
    account: 'Аккаунт',
    'sign-in': 'Войти',
    'sign-out': 'Выйти',
    'signed-in-as': 'Вы вошли как',
    username: 'Имя пользователя',
    password: 'Пароль',
    register: 'Регистрация',
    'need-account': 'Нет аккаунта? Зарегистрируйтесь',
    'have-account': 'Уже есть аккаунт? Войти',
    // Onboarding and tips
    'got-it': 'Понятно',
    'onboarding-getting-started': 'Начало работы',
    'onboarding-enter-token-message':
      'Откройте Discord Developer Portal, создайте бота и скопируйте его токен.',
    'onboarding-open-portal': 'Открыть портал',
    'onboarding-create-command-message': 'Создайте команду, чтобы у бота было действие.',
    'onboarding-go-to-commands': 'К командам',
    'onboarding-host-bot-message': 'Нажмите Войти, чтобы вывести бота онлайн!',
    webhooks: 'Вебхуки',
    debugger: 'Отладчик',
    'tip-commands-body':
      'Команды определяют, как бот отвечает на сообщения. Создайте команду, задайте триггерное слово, затем добавьте действия, например отправку сообщения.',
    'tip-webhooks-body':
      'Отправляйте сообщения в каналы Discord без хостинга бота. Вставьте URL вебхука из настроек вашего сервера Discord.',
    'tip-interactions-body':
      'Интеракции - это slash-команды Discord. Создайте одну, затем нажмите Синхронизировать, чтобы зарегистрировать ее в Discord.',
    'tip-debugger-body':
      'Состояние бота показывает постоянные переменные из ваших команд. Консоль позволяет тестировать фрагменты JavaScript в контексте бота.',
    // Command Repository strings
    'command-repository': 'Репозиторий команд',
    newest: 'Новейшие',
    'most-downloaded': 'Популярные',
    browse: 'Обзор',
    'my-shared-commands': 'Мои опубликованные команды',
    'search-commands': 'Поиск команд...',
    dismiss: 'Закрыть',
    'no-commands-in-repository': 'Команды в репозитории не найдены.',
    'try-different-search': 'Попробуйте другой поисковый запрос.',
    preview: 'Предпросмотр',
    downloads: 'загрузок',
    'no-shared-commands': 'Вы ещё не поделились ни одной командой.',
    'share-commands-hint': 'Поделитесь командами из редактора команд, чтобы увидеть их здесь.',
    'confirm-delete-shared-command': 'Вы уверены, что хотите удалить эту команду из репозитория?',
    'delete-command-failed': 'Не удалось удалить команду',
    'import-command-failed': 'Не удалось импортировать команду',
    'browse-repository': 'Обзор репозитория',
    // Share Command Modal strings
    share: 'Поделиться',
    'share-command': 'Поделиться командой',
    'command-shared-successfully': 'Команда успешно опубликована!',
    type: 'Тип',
    trigger: 'Триггер',
    'share-info': 'Ваша команда будет публично доступна в репозитории для импорта другими.',
    'no-command-selected': 'Команда не выбрана.',
    // Command Preview Modal strings
    'command-preview': 'Предпросмотр команды',
    'no-embed-configured': 'Встраивание не настроено',
    'channel-id': 'ID канала',
    'deletes-command-message': 'Удаляет сообщение команды после отправки',
    messages: 'сообщ.',
    'kicks-mentioned-user': 'Кикает упомянутого пользователя',
    'bans-mentioned-user': 'Банит упомянутого пользователя',
    'voice-mutes-mentioned-user': 'Отключает голос упомянутого пользователя',
    'requires-administrator': 'Требуется роль администратора',
    'requires-nsfw-channel': 'Требуется NSFW-канал',
    'no-actions-configured': 'Для этой команды не настроены действия.'
  }
}

// Create a writable store for the current language
export const currentLanguage = writable(DEFAULT_LANGUAGE)

// Create a derived store for the translation function
export const t = derived(currentLanguage, ($currentLanguage) => (key: TranslationKey) => {
  // Try to get the string in the current language
  const translation = translations[$currentLanguage]?.[key]
  if (translation) return translation

  // Fallback to English if the string doesn't exist in the current language
  const fallback = translations[DEFAULT_LANGUAGE]?.[key]
  if (fallback) return fallback

  // Return the key itself if no translation is found
  console.warn(`Missing translation for key: "${key}" in language: "${$currentLanguage}"`)
  return key
})

// Function to change the current language
export const setLanguage = (language: string) => {
  if (translations[language]) {
    currentLanguage.set(language)
  }
}
